language: groovy
jdk:
- oraclejdk8
before_script:
- rm -rf target
sudo: false
cache:
  directories:
  - $HOME/.grails
  - $HOME/.m2
script: ./travis-build.sh
deploy:
  provider: s3
  access_key_id: "AKIAJHDJRFA3BYNWJT4Q"
  secret_access_key:
    secure: "xpsRkLfTOqY574+OfxRpHG0lvHHgyt37Fh0vImE2fgHx/l26JMQ2um5Irk7cYvBb3LpI8Vje52BP1CC+LbMtodJfWr8I1R9FDl1AiGywRVQ8lCy5+V6bWi1tUmiA07anSIVKhM33UIxmJTaPhvZKnh6CxxYeZcBmRKSp674Di7b/lqdlkkSNQ9GS8foSnAyaYv7t655MnC2QGjjrg3ADlLdQ5zct25aCii3dQJK8NtMnxE9XbLZB2/nZH+aYJxhhTcykMQLtkB3eArIPlTE0wnSDJFF3a2z7xwAK85XUFVzGIQi87qIdvhXHYKFuHVQjCm8lNxpJY9n/qg928SdZwVx8TW/KY6fkNwdlGAlTFaPj9GS7o9HbBGKpu+GUvcFxXAnmefVUzjfnD2yqTUBGoCQbssqAynf6xxpSak+yISdzEJRrZrEImUveGdeeRsLwdKkSUSG0mQZmqHGNA4spZ01IcHExtBNfh4+HmajfSTqG+7O7C827gL9cS15mvpn+h3hUDsvsXp1shs+M9LizB2k1OraQgUsYwAf3IlsSLBiGjCTKVsBJL97zTWz2+nateY/+IyRRFmQwfUxmCw/hdHdRw8aFmFFEXi9jgBq6heV1voNci5ywWtjltQToCdARTbb5eQozVuYzd5EC86oQOOnM2JfbqI4Xw62RzeGCnUU="
  bucket: "grails.tomcat.plugin"
  skip_cleanup: true
  region: ap-southeast-2
  on:
    branch: 8.x
    
