language: groovy
jdk:
- oraclejdk8
before_script:
- rm -rf target
sudo: false
cache:
  directories:
  - $HOME/.grails
  - $HOME/.m2
script: ./travis-build.sh
deploy:
  provider: s3
  access_key_id: AKIAIFHQ2DNOFQX4SR4Q
  secret_access_key: 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
  bucket: grails.tomcat.plugin
  skip_cleanup: true
  region: ap-southeast-2
  on:
    branch: 8.x
    
    
    
