language: groovy
jdk:
- oraclejdk8
before_script:
- rm -rf target
sudo: false
cache:
  directories:
  - $HOME/.grails
  - $HOME/.m2
script: ./travis-build.sh
env:
  global:
  - secure: P7YQWNkFQeQVIkipEQ/2d1uUluP8RhU5VF9NlyxUe3hOt6wV0/9UZZhDn0OAEc0ShHHLGt6IRU/lKg51THdXXpdblet5gRWVlEDpMI38NAp95ns8PnQ39ygNM5VOAeLTWUcFRhXJ+qxLE65KUIHUhDqtuAAJaYhURId2sQWWnm/Tza//fDOQmFjNgyohan1CkCCAyjpIm9er237QsqQdZVrGPnXbnk+x550DLQ0p0mFjEMV86v5OVxwRAYrfxlFcxWmVP1+TwTiW5IhOwn8qbFibd+nHkqIgcsKXzAo/0GH2KdigV/q4d2RhPsPoShpdNx+k/9gcytoIrnXrKHKvUVGSBbwsPSea8qQe4J/1phCPlFrg5+H5fO8DHhH3yqGP0UJpFJWr2Be3nIvzHatbsusmssKPYrdnpACGnvgUOSxOmtaOX0GBC0Y2vKt3Iu5L2FitOuIseSNalVU34KrjY7G9+Lv5eem2iiejSRpbLlLN3k4+N21XOZjuho+20BL13k3ogXusSjnA1bRKCAQNfNZpw93TQ1Cdfp8tXe3q+mdl/475yVnUd+37nPgh29nNewq5lvUC+TvhB/6o3pJuSO/W3Zd3ykb8moFz8WKCB9hAV0kfYLLAk85sjfk4jbb7uvYqrl9HFJ/o5NIsOTvc0gklLUUJtQnjYVUmpn2RucQ=
  - GIT_DEPLOY_REPO=https://$GH_TOKEN@github.com/magnusbutlin/magnusbutlin.github.io
