language: groovy
jdk:
- oraclejdk8
before_script:
- rm -rf target
sudo: false
cache:
  directories:
  - $HOME/.grails
  - $HOME/.m2
script: ./travis-build.sh
deploy:
  provider: s3
  access_key_id: AKIAJHDJRFA3BYNWJT4Q
  secret_access_key:
    secure: CnBYJ821syLhknTZT88DYHKyNdoOWwlbJ1H2hwdbWfGq4P8mamVi/IUR4P+m5Va/U4XfT1ez0F+pzm289mYxhPDxoHOB3v01ObKI1sQsnaQyHon/LofI0lion+91z6WtNzNrq/s+pDCdNyz3uHlamj+ROrClJHEm+KJog3kVIQRi7XISkez4Gk9X/bFbdf5dJ/BCvXXYWNAd/23BpRE8eEdVbuKk7k4T0aJvfgNbIBVQPTU7Ge6CwX+KqDl3pjUEHuOtFSkGAyfVLymIEoq3V91gz5KeIUOYDLbzfQHeSxRKc1T7lWKfYmTZ8ZhJ/HRiBZE4w98Ddpg44NXBjV5MkA17ZF4/EQBwJXGEcIGlvRXynXBFHZZAd4rwEVx4EtLzfg2z3EqjqX8tMLKHpf1AJFsiBzOlLTcU3riCewFs0w+/lvrDfrcZ9I6JabfHhhn/BYGjx9kqCVpuLpoVYDd3Hcmp+fuTh2nzVugncqAm07c3L6XsoJIjyDR4XWzh7NdovJOIZ9AEHjKxuTFAMd+CRX/aZJaI2dcXGcP51wB2p/zQQK2AbBpIFmxkglOXo71a04MvxatRjm6uXDicYSQ+xdTvx/e0nteLR60PE3Gp/Or9597MwJR0CQ70B1WUvjUOX513YZXuVOQbpPzMOMF45NXzgZJXLAzSbdIQAECUK5c=
  bucket: grails.tomcat.plugin
  skip_cleanup: true
  region: ap-southeast-2
  on:
    branch: 8.x
    
