language: groovy
jdk:
- oraclejdk8
before_script:
- rm -rf target
sudo: false
cache:
  directories:
  - $HOME/.grails
  - $HOME/.m2
script: ./travis-build.sh
env:
  global:
  - secure: h6TbCDIqYQl2XBnAN9IitZ6Cy7Ospxk8HhhNWTo+TvVbjD+Uur4AJ4GOwwsQXSnXDmTqwma8R/fPe/a9843ua6Wcrjvt8/GYosC6l5WcAPOlhKC+eHrziR7JIulb4CYWiSw4vhfQaDhQ2ckkE1GVLo6Utc4qbaeQ61MP4H4SK9TKFApgsD4HHogVV5xc+XJVHihvatdyMuBqiuPc1Uvmml9nGadLx5z/fH+Zi3Cbh51OXJa2LaoXUiP8tkLBSgRkp6jh+vUjY/o3Ru9W5pTlFfdHq5Y5jS04TfF7mcS5DEWWbJUPiLxdnjQyvCfeDhqMAdfN/1dF9lGllX7EecDWnzb3DK8FnwbCrvon0tbiTkZorVF/SWXRv0DszLI2teUBXIe21cuzkukmPykCDJfLcEMbcmdicmAaqT1Ldz/vtkrOBgSiJY7noGVPmwAX8lyslm2959614ydDhh/9FPku31QkV3WPqiMGvdT25xRFUZXRIn66zX75aA/s48gkDYy7bqQwTS6YazJvdf041Sy0TWD+Y0Aev02ekcIOBaTVvwZCclgkfRC7DsMXmDfVc7bJ6Wi9Wyc2e6amayg4ek9qvdEIv/T0471IEhU1OCGz9npwB26xuFD9laMHWkVu5h+nAQ+PwnBVeKmLUImFctX6TmtaOIxYCwZC1YIGDjFoMTE=
  - GIT_DEPLOY_REPO=https://$GH_TOKEN@github.com/magnusbutlin/magnusbutlin.github.io
