language: groovy
jdk:
- oraclejdk8
before_script:
- rm -rf target
sudo: false
cache:
  directories:
  - $HOME/.grails
  - $HOME/.m2
script: ./travis-build.sh
deploy:
  provider: s3
  access_key_id: AKIAJHDJRFA3BYNWJT4Q
  secret_access_key:
    secure: xTuA5qX4upNBuij7f7GOuDqfk6O7zJxBvIEyEmew+fSk9alRth6DO4HgqevebCshvn9BF+cIkgw8yjDK4PxFNCcrtVEoDFR4mSXtLlNTqgQ4Q7p3BRPMcQKhxqpX9wZ3CUSgXiJ75UnYjoBOo7lngIu3Kq9SwBKu7ry9GImO47G9+3KfUP6p4sQuB4+h3hKkpLbMFIC6HBtiz60Y+IBgS8MGQVKlW0FkkWtlGKL8hC1CTJMxafrBK1vBnyOIl/MBe8irbWVlY/C9Rd76fQzQfaPj97vLGgMYC3yvVZI8eIYL+OGEddiOup7INmxojmFrsGAoSJgeZ9wbPHQ6fUvZRhHHjqv1RGqjUmt6ej6WBkuo+rbF6rI0u+TY4etaJvOo1v+7R2HZBY9tkeCLqBfpyoKVLznlqlBGuvvUry/XZwOYmJ2rG0ZKESVKoqTcL4bJA+C8FjyC8nW0U9tVzsLk6JyINZ97jyoRX/rPovY49LtPryBgrp9UbpuFSqWPopHP3x770Rc+mfEcmkFboWCaM+7UCLkkOtLrAyCmAslFMsG9SyFf3VI6SpDtTUkAgq8ditAj16+PGkuEHtqbzMKtZcgAFmBbUQJbddOFRF5Xt91oS1oioTWzrxVqPpWycesdzYzJycVMsN+1jtSyAYLWvdw65zdIwpsV9DTCP6xEph0=
  bucket: grails.tomcat.plugin
  skip_cleanup: true
  region: ap-southeast-2
  on:
    branch: 8.x
    
