language: groovy
jdk:
- oraclejdk8
before_script:
- rm -rf target
sudo: false
cache:
  directories:
  - $HOME/.grails
  - $HOME/.m2
script: ./travis-build.sh
deploy:
  provider: s3
  access_key_id: AKIAIFHQ2DNOFQX4SR4Q
  secret_access_key:
    secure: lCK24NGMsD2L+xYwtk/CpJcTwCqr8fxYTjThIHUYsoGFbUD50mAd8K81DLPVuQsUeEYTDxvd2WrUAgGTPZ9Wcv9smVJVhOJzdYbFdW2Z7xbs7zKfeiOS80s9xcyRnRjQQFEvp44jnJ4oXSg/V701Fo4eLfRfThwcgYRRR4Y6W7ocybg3q4t1kq5TifgR349/pslw5uHWvbTNYTp6JYIyFpErli9Kg2UHMxQ56a5TF48o+m6RHURtpIJ3Dri3tL4bXpiJK1WkNhddBGOSwNlBZpBuSGd5HAAuBtKlrbsA1n24sMFUD6l9fxlfJuU5hRbP1ti3bXysllC+jLLplY6hWcj4tTNz2PjEOK/3/IuwjXiCh1zQYsZ91fik5MkPg0xVODU1HHtn5xsmFhGXPbFcm75Ehef0h9+nAxQYigNr/XoBxdacLInbEpiQEYI/BwVfW3/GSd9MYuS2Lw7t1vJlWmhz0taYXZTQwA4S/ctfUpN39M6ZdkbGAe7HhO2Mx1lZzkutuu3G6vUARUBHh+rv2801dBOUX9oiTHC+pvj3JnCfwv/UAKgrK26ccVohLAVxpF0peiUFrUCwW6XWI1vOYdOiVlR0OQ/z8AKm5J12zAAaCwV/g5P6bgdAVGWERtiZVRJz1tu5AfONFvL2c2EqUPDYfQLZnupi7dd4QFSuxn4=
  bucket: grails.tomcat.plugin
  skip_cleanup: true
  region: ap-southeast-2
  on:
    branch: 8.x
    
    
    
